name: CI

on: [push, pull_request]

jobs:

  composer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
      - run: composer validate
      - run: composer install --prefer-dist --no-progress --no-suggest
      - run: composer test

  node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: yarn
      - run: yarn eslint
      - run: yarn build
